// Conversation starters for different languages
export const conversationStarters = {
  english: [
    "Hi!",
    "Hello!",
    "Hey there!",
    "Good morning!",
    "Good afternoon!",
    "Good evening!",
    "What's up?",
    "How's it going?",
    "How are you?",
    "Nice to meet you!",
    "How are you today?",
    "How's your day?",
    "What's new?",
    "How have you been?",
    "Hope you're doing well!",
  ],
  spanish: [
    "¡Hola!",
    "¡Buenos días!",
    "¡Buenas tardes!",
    "¡Buenas noches!",
    "¿Cómo estás?",
    "¿Qué tal?",
    "¡Mucho gusto!",
    "¿Cómo te va?",
    "¿Qué hay de nuevo?",
    "¿Cómo has estado?",
    "¡Espero que estés bien!",
    "¿Cómo estuvo tu día?",
    "¿Qué planes tienes?",
    "¡Qué gusto verte!",
    "¿Todo bien?",
  ],
  french: [
    "Salut!",
    "Bonjour!",
    "Bonsoir!",
    "Comment allez-vous?",
    "Comment ça va?",
    "Enchanté!",
    "Comment vous portez-vous?",
    "Quoi de neuf?",
    "Comment avez-vous été?",
    "J'espère que vous allez bien!",
    "Comment s'est passée votre journée?",
    "Ça va bien?",
    "Comment ça se passe?",
    "Ravi de vous voir!",
    "Tout va bien?",
  ],
  german: [
    "Hallo!",
    "Guten Morgen!",
    "Guten Tag!",
    "Guten Abend!",
    "Wie geht es Ihnen?",
    "Wie geht's?",
    "Freut mich!",
    "Wie läuft's?",
    "Was gibt's Neues?",
    "Wie ist es Ihnen ergangen?",
    "Ich hoffe, es geht Ihnen gut!",
    "Wie war Ihr Tag?",
    "Alles in Ordnung?",
    "Schön Sie zu sehen!",
    "Wie steht's?",
  ],
  italian: [
    "Ciao!",
    "Salve!",
    "Buongiorno!",
    "Buon pomeriggio!",
    "Buonasera!",
    "Come va?",
    "Come stai?",
    "Piacere di conoscerti!",
    "Come stai oggi?",
    "Com'è stata la tua giornata?",
    "Cosa c'è di nuovo?",
    "Come sei stato?",
    "Spero che tu stia bene!",
    "Che fai di bello?",
    "Come procede?",
  ],
  portuguese: [
    "Olá!",
    "Oi!",
    "Bom dia!",
    "Boa tarde!",
    "Boa noite!",
    "Como vai?",
    "Tudo bem?",
    "Prazer em conhecê-lo!",
    "Como você está hoje?",
    "Como foi seu dia?",
    "O que há de novo?",
    "Como você tem estado?",
    "Espero que esteja bem!",
    "Como está indo?",
    "Tudo certo?",
  ],
  russian: [
    "Привет!",
    "Здравствуйте!",
    "Здорово!",
    "Доброе утро!",
    "Добрый день!",
    "Добрый вечер!",
    "Как дела?",
    "Как поживаете?",
    "Как вы?",
    "Приятно познакомиться!",
    "Как дела сегодня?",
    "Как ваш день?",
    "Что нового?",
    "Как поживали?",
    "Надеюсь, у вас все хорошо!",
  ],
  japanese: [
    "こんにちは！",
    "おはよう！",
    "こんばんは！",
    "元気ですか？",
    "調子はどう？",
    "はじめまして！",
    "今日はどうでしたか？",
    "最近どうですか？",
    "お元気でしたか？",
    "元気でいてくださいね！",
    "何か新しいことありますか？",
    "どうですか？",
    "いかがですか？",
    "お疲れさまです！",
    "よろしくお願いします！",
  ],
  korean: [
    "안녕하세요!",
    "안녕!",
    "좋은 아침!",
    "좋은 오후!",
    "안녕히 주무세요!",
    "어떻게 지내세요?",
    "잘 지내세요?",
    "만나서 반가워요!",
    "오늘 어떠세요?",
    "하루 어땠어요?",
    "무슨 일 있어요?",
    "어떻게 지내셨어요?",
    "잘 지내시길 바라요!",
    "어떻게 지내고 있어요?",
    "모든 게 잘 되고 있나요?",
  ],
  chinese: [
    "你好！",
    "早上好！",
    "下午好！",
    "晚上好！",
    "你怎么样？",
    "你好吗？",
    "很高兴见到你！",
    "你今天怎么样？",
    "你的一天怎么样？",
    "有什么新鲜事吗？",
    "你最近怎么样？",
    "希望你一切都好！",
    "你过得怎么样？",
    "一切都好吗？",
    "最近如何？",
  ],
  arabic: [
    "مرحبا!",
    "صباح الخير!",
    "مساء الخير!",
    "كيف حالك؟",
    "كيف الأحوال؟",
    "سعيد بلقائك!",
    "كيف كان يومك؟",
    "ما الجديد؟",
    "كيف كنت؟",
    "أتمنى أن تكون بخير!",
    "كيف الأمور؟",
    "هل كل شيء على ما يرام؟",
    "كيف تسير الأمور؟",
    "أهلا وسهلا!",
    "كل عام وأنت بخير!",
  ],
};

// Get initial hint based on language - returns a random conversation starter
export const getInitialHint = (language) => {
  const starters =
    conversationStarters[language] || conversationStarters.english;
  const randomIndex = Math.floor(Math.random() * starters.length);
  return starters[randomIndex];
};
